# Site settings
title: Reno的博客
email: qxl19920213@163.com
description: Reno's Blogs

# > # this means to ignore newlines until "baseurl:"
github_username: luopoqinhuai
permalink: /:year/:month/:day/:title/



# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/luopoqinhuai/luopoqinhuai.github.io/blob/master/

# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/luopoqinhuai/


# Build settings
markdown: kramdown

# highlight
highlighter: pygments
# highlighter: rouge
# highlighter: false
port: 5001
